### ISSUE TITLE
Is it possible to generate generic mapping functions?

### ISSUE THREAD

**Issue by Thecentury** [eiriktsarpalis/TypeShape#34]
Is it possible to generate mapping functions for generic types over one of their generic arguments?

Given types

```fsharp
type Record<'t> = {
    List : List<'t>
    Option : Option<'t>
    Int : int
    T : 't
}
type G<'a, 't> =
    | X of int
    | G of Record<'t>
    | Z of 'a
```

get a function that will perform this kind of mapping:

```fsharp
let rMap (f : 'a -> 'b) (r : Record<'a>) =
    {
        List = List.map f r.List
        Option = Option.map f r.Option
        Int = r.Int
        T = f r.T
    }

let gMap (f : 'a -> 'b) (g : G<'t, 'a>) =
    match g with
    | X i -> X i
    | G r -> G (rMap f r)
    | Z a -> Z a
```

If you think that it is possible, could you please give some ideas on how this can be done?

**Comment by eiriktsarpalis** [comment]
A similar gmap function [already exists in the library](http://www.tryfsharp.org/Create?codeUrl=http://fssnip.net/raw/7XZ). Note however that the mapper function must be of type `'a -> 'a`.

I'm not sure whether it can be meaningfully extended to arbitrary mapper types (`'a -> 'b`), since it can only be applied to fields that are generic parameters. TypeShape is agnostic w.r.t. generic types, so it is almost certain that a certain degree of reflection might be necessary.

**Comment by Thecentury** [comment]
Hi Erik, thank you, I will try some of these approaches.
