### ISSUE TITLE
Recursive Poco type causes exception

### ISSUE THREAD

**Issue by object** [eiriktsarpalis/TypeShape#4]
### Description

The following type causes either NullReferenceException or StackOverflowException.

type [&lt;AllowNullLiteral&gt;] RecursivePocoType() =
    member val Text : string = null with get, set
    member val This : RecursivePocoType = null with get, set

### Repro steps

1. Define the type as described above

2. Create value printer:
let (prt : RecursivePocoType -&gt; string) = mkPrinter&lt;RecursivePocoType&gt;()

3. Create a value
let pt = RecursivePocoType()
pt.Text &lt;- "abc"

4. Print the value:
prt pt

### Expected behavior

Printed value.

### Actual behavior

Null reference exception. 

This happens due to pt.This not being set. If I set it to itself (pt), the StackOverflowException is raised.

**Comment by eiriktsarpalis** [comment]
Thanks. I imagine the stack overflow error happens when the `This` field is assigned to the object itself. Please note that these are samples intended to showcase the capabilities of the library and thus should not be treated as full-fledged implementations or as part of the library itself. In other words, adding support for `null` values and cyclic objects is left as an exercise to the reader. This would require changing the signature of generated lambdas so that they also thread an instance of [`ObjectIdGenerator`](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.objectidgenerator(v=vs.110).aspx) class, for instance.

That said, I would like to take the time to write a production-grade value printer using TypeShape at some point, though this would obviously live as a standalone project.
